[package]
name = "polywrap-tracing-rs"
version = "0.1.0"
description = "Polywrap Core Tracing"
authors = ["Kobby Pentangeli <kobbypentangeli@gmail.com>"]
repository = "https://github.com/polywrap/monorepo"
license = "MIT"
edition = "2018"

[dependencies]
futures = "0.3.16"
opentelemetry = "0.16.0"
opentelemetry-otlp = "0.9.0"
opentelemetry-zipkin = "0.14.0"
serde = "1.0.127"
serde_json = "1.0.66"

[lib]
crate-type = ["cdylib", "rlib"]