[package]
name = "polywrap-tracing-rs"
version = "0.1.0"
description = "Polywrap Core Rust Tracing"
authors = ["Kobby Pentangeli <kobbypentangeli@gmail.com>"]
repository = "https://github.com/polywrap/monorepo"
license = "MIT"
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
futures = "0.3.16"
serde_json = "1.0.66"
