[package]
name = "query"
version = "0.1.0"
description = "Query module of test-api implementation"
authors = [
  "Kobby Pentangeli <kobbypentangeli@gmail.com>",
  "Jordan Ellis <jelli@dorg.tech>"
]
repository = "https://github.com/polywrap/monorepo"
license = "MIT"
edition = "2021"

[features]
w3invoke = []

[dependencies]
polywrap-wasm-rs = { version = "0.0.1-prealpha-dev.37.4", path = "../../../../../../../wasm/rs"}
serde = { version = "1.0", features = ["derive"] }

[lib]
crate-type = ["cdylib", "rlib"]

[profile.release]
opt-level = 'z'
lto = true
panic = 'abort'