[package]
name = "polywrap-core-rs"
version = "0.1.0"
description = "Core Polywrap Rust Package"
authors = ["Kobby Pentangeli <kobbypentangeli@gmail.com>"]
repository = "https://github.com/polywrap/monorepo"
license = "MIT"
edition = "2018"

[dependencies]
futures = "0.3.16"
polywrap-tracing-rs = { path = "../tracing" }

[lib]
crate-type = ["cdylib", "rlib"]