[package]
name = "polywrap-core-rs"
version = "0.1.0"
description = "Core Polywrap Rust Package"
authors = ["Kobby Pentangeli <kobbypentangeli@gmail.com>"]
repository = "https://github.com/polywrap/monorepo"
license = "MIT"
edition = "2018"

[dependencies]
futures = "0.3.16"
graphql-parser = "0.3.0"
regex = "1.5.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[lib]
crate-type = ["cdylib", "rlib"]