[package]
name = "polywrap-core-rs"
version = "0.1.0"
description = "Core Polywrap Rust Package"
authors = ["Kobby Pentangeli <kobbypentangeli@gmail.com>"]
homepage = "https://polywrap.io"
documentation = "https://docs.polywrap.io"
repository = "https://github.com/polywrap/monorepo"
license = "MIT"
edition = "2021"

[dependencies]
futures = "0.3.18"
graphql-parser = "0.4.0"
mustache = "0.9.0"
regex = "1.5.4"
schemafy = "0.6.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
valico = "3.6.0"

[lib]
crate-type = ["cdylib", "rlib"]

[profile.release]
opt-level = 'z'
lto = true
panic = 'abort'