[package]
name = "polywrap-client-rs"
version = "0.1.0"
description = "Polywrap Rust Client"
authors = ["Kobby Pentangeli <kobbypentangeli@gmail.com>"]
homepage = "https://polywrap.io"
documentation = "https://docs.polywrap.io"
repository = "https://github.com/polywrap/monorepo"
license = "MIT"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[lib]
crate-type = ["cdylib", "rlib"]

[profile.release]
opt-level = 'z'
lto = true
panic = 'abort'