# Example of overriden configuration

version: '3'
services:
  dev-server:
    env_file: './.env'
    environment:
      ganache: 'ganache:${ETHEREUM_PORT}'
    ports:
      - '${DEV_SERVER_PORT}:${DEV_SERVER_PORT}'
  ganache:
    env_file: './.env'
    ports:
      - '${ETHEREUM_PORT}:8545'
    command: -l 8000000 --networkId 1576478390085 --deterministic --hostname=0.0.0.0
  ipfs:
    env_file: './.env'
    ports:
      - '5001:5001'
      - '8080:8080'
