[package]
name = "bigint-type"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# The Wasmer API
wasmer = "2.1.1"
wasmer-compiler-cranelift = "2.1.1"
wasmer-engine-universal = "2.1.1"
