version: "3"
services:
  dev-server:
    env_file: "./.env"
    environment:
      ganache: "ganache:${ETHEREUM_PORT}"
    image: "benefacto/web3-api_dev-server"
    links:
      - ganache
    ports:
      - "${DEV_SERVER_PORT}:${DEV_SERVER_PORT}"
  ganache:
    command: -l 8000000 --networkId 1576478390085 --deterministic --hostname=0.0.0.0
    env_file: "./.env"
    image: "trufflesuite/ganache-cli"
    ports:
      - "${ETHEREUM_PORT}:8545"
  ipfs:
    env_file: "./.env"
    image: "ipfs/go-ipfs:v0.4.23"
    ports:
      - "5001:5001"
      - "8080:8080"
