version: "3"
services:
  # A dev-server service is spun up by default 
  ganache:
    command: -l 8000000 --networkId 1576478390085 --deterministic --hostname=0.0.0.0
    env_file: "./.env"
    image: "trufflesuite/ganache-cli"
    ports:
      - "${ETHEREUM_PORT}:8545"
  ipfs:
    env_file: "./.env"
    image: "ipfs/go-ipfs:v0.4.23"
    ports:
      - "5001:5001"
      - "8080:8080"
