[package]
name = "query"
version = "0.1.0"
description = "Query module of json-type e2e test"
authors = [
  "Kobby Pentangeli <kobbypentangeli@gmail.com>",
  "Jordan Ellis <jelli@dorg.tech>"
]
repository = "https://github.com/polywrap/monorepo"
license = "MIT"
edition = "2021"

[dependencies]
polywrap-wasm-rs = { version = "0.0.1-prealpha-dev.37.4", path = "../../../../../../wasm/rs" }
serde_derive = "1.0.130"

[lib]
crate-type = ["cdylib"]

[profile.release]
opt-level = 'z'
lto = true
panic = 'abort'
