name: changelog-command
on:
  repository_dispatch:
    types: [changelog-command]
jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:

      - name: Create variable to store command
        id: vars
        run: |
            echo ::set-output name=changelog-desc::${{github.event.client_payload.slash_command.args.all }}
            echo ::set-output name=is-formatted::${{ ( 
              startsWith(github.event.client_payload.slash_command.args.all, 'CHfeat:') ||
              startsWith(github.event.client_payload.slash_command.args.all, 'changelog-feat:') || 
              startsWith(github.event.client_payload.slash_command.args.all, 'changelog-fix:') ||
              startsWith(github.event.client_payload.slash_command.args.all, 'changelog-chore:') ||
              startsWith(github.event.client_payload.slash_command.args.all, 'changelog-docs:') ||
              startsWith(github.event.client_payload.slash_command.args.all, 'changelog-style:') ||
              startsWith(github.event.client_payload.slash_command.args.all, 'changelog-refactor:') ||
              startsWith(github.event.client_payload.slash_command.args.all, 'changelog-perf:') ||
              startsWith(github.event.client_payload.slash_command.args.all, 'changelog-test:')) }}
  
      - name: Exit if not formatted
        if: steps.vars.outputs.is-formatted == 'false'
        run: |
              echo "${{steps.vars.outputs.is-formatted}}"
              exit 1

      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_ACCESSS_TOKEN }}
          repository: ${{ github.event.client_payload.pull_request.head.repo.full_name }}
          ref: ${{ github.event.client_payload.pull_request.head.ref }}

      - name: Add reaction
        uses: peter-evans/create-or-update-comment@v1
        with:
          token: ${{ secrets.REPO_ACCESSS_TOKEN }}
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          reaction-type: hooray


      - name: Commit to the PR branch
        run: |
          git config --global user.name 'actions-bot'
          git config --global user.email '58130806+actions-bot@users.noreply.github.com'
          git commit --allow-empty -m "${{ steps.vars.outputs.changelog-desc }}"
          git push

      - name: Create comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          token: ${{ secrets.REPO_ACCESSS_TOKEN }}
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          issue-number: ${{ github.event.client_payload.github.payload.issue.number }}
          body: |
            Hello @${{ github.event.client_payload.github.actor }}!
            added the following update to the upcoming version in the changelog:
            `${{ steps.vars.outputs.changelog-desc }}`
      
      
