name: changelog-command
on:
  repository_dispatch:
    types: [changelog-command]
jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:

      - name: Create variable to store command
        id: vars
        run: |
            echo ::set-output name=changelog-desc::${{github.event.client_payload.slash_command.args.all }}
            echo ::set-output name=is-formatted::${{ !( 
              startsWith(steps.vars.outputs.changelog-desc, 'feat:') || 
              startsWith(steps.vars.outputs.changelog-desc, 'fix:') ||
              startsWith(steps.vars.outputs.changelog-desc, 'chore:') ||
              startsWith(steps.vars.outputs.changelog-desc, 'docs:') ||
              startsWith(steps.vars.outputs.changelog-desc, 'style:') ||
              startsWith(steps.vars.outputs.changelog-desc, 'refactor:') ||
              startsWith(steps.vars.outputs.changelog-desc, 'perf:') ||
              startsWith(steps.vars.outputs.changelog-desc, 'test:')) }}
              
      - name: Checks feat
        if: startsWith(steps.vars.outputs.changelog-desc, 'feat:')
        run: echo "Contains feat:"
        
      - name: Checks not feat
        if: ${{ !(startsWith(steps.vars.outputs.changelog-desc, 'feat:')) }}
        run: echo "Does not contain feat:"
  
      - name: Exit if not formatted
        if: steps.vars.outputs.is-formatted == false
        run: |
              echo "${{steps.vars.outputs.is-formatted}}"
              exit 1

      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_ACCESSS_TOKEN }}
          repository: ${{ github.event.client_payload.pull_request.head.repo.full_name }}
          ref: ${{ github.event.client_payload.pull_request.head.ref }}

      - name: Add reaction
        uses: peter-evans/create-or-update-comment@v1
        with:
          token: ${{ secrets.REPO_ACCESSS_TOKEN }}
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          reaction-type: hooray


      - name: Commit to the PR branch
        run: |
          npm i --save-dev standard-version
          git config --global user.name 'actions-bot'
          git config --global user.email '58130806+actions-bot@users.noreply.github.com'
          git commit --allow-empty -m "${{ steps.vars.outputs.changelog-desc }}"
          git push
          npm run release
          git push --follow-tags origin changelog-automate

      - name: Create comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          token: ${{ secrets.REPO_ACCESSS_TOKEN }}
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          issue-number: ${{ github.event.client_payload.github.payload.issue.number }}
          body: |
            Hello @${{ github.event.client_payload.github.actor }}!
            added the following update to the upcoming version in the changelog:
            `${{ steps.vars.outputs.changelog-desc }}`
      
      
