name: changelog-command
on:
  repository_dispatch:
    types: [changelog-command]
jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Add reaction
        uses: peter-evans/create-or-update-comment@v1
        with:
          token: ${{ secrets.REPO_ACCESSS_TOKEN }}
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          reaction-type: hooray

      - name: Create variable to store command
        id: vars
        run: echo ::set-output name=changelog-desc::${{github.event.client_payload.slash_command.args.all }}

      - name: Create comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          token: ${{ secrets.REPO_ACCESSS_TOKEN }}
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          issue-number: ${{ github.event.client_payload.github.payload.issue.number }}
          body: |
            Hello @${{ github.event.client_payload.github.actor }}!
            added the following update to the upcoming version in the changelog:
            `${{ steps.vars.outputs.changelog-desc }}`

      - name: Commit changelog desc
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: ${{ steps.vars.outputs.changelog-desc }}

      - name: Automate changelog
        run: npm run release
      
      